my_tuple = (1,2,3,4)
print(my_tuple)
print(my_tuple[2])
print(my_tuple[0:3])
print(len(my_tuple))
del my_tuple
my_tuple2 = (21,34,65,97,35,34)
print(my_tuple2)
print(max(my_tuple2))
print(min(my_tuple2))
print(sum(my_tuple2))
print(sum(my_tuple2)/len(my_tuple2))
my_tuple2.index(35)
print(my_tuple2.index(35))
print(my_tuple2.count(34))

my_tuple3 = ("Ann,Mary,Ann,Kim,Loise,Tasha")
print(my_tuple3)
print(my_tuple3.index("Kim"))
print(my_tuple3.count("Ann"))